name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust (Stable)
      uses: dtolnay/rust-toolchain@stable

    - name: Build
      run: cargo build --verbose

    - name: Install `cargo-tarpaulin`
      run: cargo install cargo-tarpaulin --locked

    - name: Run Test Coverage
      run: cargo tarpaulin --out xml --output-file coverage.xml
      
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}  
        files: coverage.xml
        fail_ci_if_error: true
